modules: lnbits: Disable MemoryDenyWriteExecute, causes crash in pynostr
MemoryError: Cannot allocate write+execute memory for ffi.callback().
You might be running on a system that prevents this. For more
information, see
https://cffi.readthedocs.io/en/latest/using.html#callbacks

/nix/store/.../lib/python3.12/site-packages/pynostr/key.py", line 211, in <module>